[tool.poetry]
name = "e-commerce-shop"
version = "0.1.0"
description = "Интернет-магазин - домашняя работа по ООП"
authors = ["MikhailZizganov <mihazizganov@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^25.12.0"
flake8 = "^7.3.0"
pytest = "^9.0.2"
pytest-cov = "^7.0.0"
mypy = "^1.19.1"
mypy-extensions = "^1.1.0"
isort = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"